### ISSUE TITLE
Ability to query Message Alert entity as regards delivery status

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#139]
Message delivery status is a property of the Patron entity, so it is not possible to query the delivery status by accessing the Message\Alert entity (for example if the message has been sent to via Patron Category)

**Comment by franciscave** [comment]
At the Technical Panel meeting on 27/02/2019 we agreed that some detailed work is needed to add this feature, with particular attention to the status of messages sent to multiple patrons.

**Comment by franciscave** [comment]
The Technical Editors discussed this briefly. What is proposed probably contains more information - and more duplicate information that can be retrieved from Patron records - than is needed. A suggestion would be to modify the proposal to remove E15D16.3.2 Delivery status and the whole of E15D16.4.5. But in that case E15D16.3.1 simply duplicates E15D11, which would mean that E15D16.3 is redundant. A simpler structure would therefore be:

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*   | *Description*                  |
|------------|----------------------------|------------|---------|------------|--------------------------------|
| *E15C16*    | Delivery information        |                  | 0-1      |                  |                                               |
| E15D16.1 | Total delivered                 |                  | 0-1       | Integer     | Number of Patrons to whom this message/alert has been delivered |
| E15D16.2 | Total acknowledged         |                 | 0-1        | Integer     | Number of Patrons from whom acknowledgements of this message/alert have been received |
| *E15C16.3* | Delivery to Patron category |            | 0-n         |                 | Delivery status for specific category of Patron |
| E15D16.3.1 | Category name              |                | 1            | String       |                                               |
| E15D16.3.2 | Total Patrons in category  |               | 0-1       | Integer     | Number of Patrons at whom this message/alert is aimed |
| E15D16.3.3 | Total delivered               |                | 0-1         | Integer     | Number of Patrons in category to whom this message/alert has been delivered |
| E15D16.3.4 | Total acknowledged       |               | 0-1         | Integer     | Number of Patrons in this category from whom acknowledgements of this message/alert have been received |

The disadvantage with this simpler structure is that the delivery status information is only available in aggregated form. To determine whether a message/alert has been delivered to a particular Patron, it will still be necessary to retrieve the Patron record.

**Comment by franciscave** [comment]
To handle the cases where messages are sent to Patrons related to specified Loans or Reservations (message/alert audience code values '03' or '04'), the above could be extended as follows:

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*   | *Description*                  |
|------------|----------------------------|------------|---------|------------|--------------------------------|
| *E15C16.4* | Delivery to related Patrons |            | 0-n         |                 | Delivery status for Patrons related to the specified Loans or Reservations |
| E15D16.4.1 | Total Patrons       |               | 0-1       | Integer     | Number of Patrons at whom this message/alert is aimed |
| E15D16.4.2 | Total delivered               |                | 0-1         | Integer     | Number of Patrons to whom this message/alert has been delivered |
| E15D16.4.3 | Total acknowledged       |               | 0-1         | Integer     | Number of Patrons from whom acknowledgements of this message/alert have been received |

A single composite is all that is needed, since the message/alert audience cannot be both '03' and '04'.
