### ISSUE TITLE
Note type within loan-restriction type

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#156]
loan-restriction includes the following sub-components: restriction-type, value, and note.

In the documentation, note is a string, in the schema it is assigned the more generic note element (which has the sub-components of note-type, date-time, and note-text). I suspect that this is just due to a name clash of "note" (as we are use the top-level elements pattern for the xml schema) which wasn't picked up when we added complexity to the more generic note element.

**Comment by franciscave** [comment]
Since 'note' is generally a composite, I think that I must have assumed that in this particular instance the element 'note' would be defined locally instead of globally, but it isn't really a good idea to have two elements of the same name with different structures. 

Ideally, we would like to rename 'note' in this context to be 'restriction-note', a simple data element. However, this would break backwards-compatibility, so maybe we should modify the Data Framework and XML Binding to include a composite that corresponds to what we currently have in the schema, but immediately deprecate it, and add a new simple data element that can be called 'restriction-note' in the XML Binding. 

Am I over-complicating things?

**Comment by mdovey** [comment]
As regards renaming it - I'd be tempted to regard that as mopping up some errors whilst we move to semantic versioning and include it in 1.1, even if this isn't quite compliant with semantic versioning. Especially if we agree to do the same in issue #162 

If we decide to leave such renaming for a 2.x.x version, then it would be easier to replace

             <xs:element ref="note" minOccurs="0"/>

with 

             <xs:element name="note" type="nonEmptyString" minOccurs="0"/>

in the schema to resolve this (as a correction to the non-normative schema file to match the normative documentation can be regarded as a patch\bug fix update).

**Comment by franciscave** [comment]
OK, I'll change the name of element E02D09.3 from 'note' to 'restriction-note' in the XML binding.
