### ISSUE TITLE
E14D05.2 missing in xml schema, and cardinality discrepancy between data framework and xml binding documentation

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#161]
E14D05.2 (contact-name within assoicated-contact) is missing from the xml schema.

Also in the dataframework the cardinality for E14D05.2 is given as 1, whereas in the XML binding it is given as 0-1.

In any case, why is this needed given that contact-ref is a mandatory element?

**Comment by franciscave** [comment]
The reason that contact name is mandatory is that we decided for v1.0.1 to remove contact name (E09D02) from the Contact entity. This is because we decided that the contact entity doesn't name the contact person but simply specifies their contact details (addresses of various kinds). That's why we added E03D22 in v1.0.1. Since we are assuming that an institutional contact must have a name (it doesn't have to be a personal name, it could be just "The Librarian", or even the name of a team or organisation), the element E14D05.2 has to be mandatory.
