### ISSUE TITLE
Type for R00D05.3 in xml schema not specific enough

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#162]
element-ref (R00D05.3) in lcf-exception is a nonEmptyString where for consistency it should be of type lcfEntityReference

**Comment by franciscave** [comment]
Hmm, I'm not sure that this was the original intention. As I understand the original intention, it is not an _entity_ reference that is reported in the exception report, it is an identifier of the LCF _element_ in the request that was the source of the error (if this can be identified). The identifier is a string such as 'Q00D07' if the exception is caused by their being an invalid Request ID in the request. If the entity _reference_ in a request Q01 were invalid, then the string would be 'Q01D02'. If the entity _type_ in a request Q01 were invalid, then the string would be 'Q01D01'.

**Comment by mdovey** [comment]
Ah, I see.

In which case, I think this was missed when we tried to standardise the use of the "-ref" suffix to indicate an entity reference.

Could we rename this to element-id for consistency?

**Comment by franciscave** [comment]
Agreed.
