### ISSUE TITLE
Classification inconsistencies in manifestation between Data framework and XML bindings

### ISSUE THREAD

**Issue by kjeyakanthan** [bic-org-uk/bic-lcf#188]
Can we please update the XML bindings to match the Data framework. 

I personally like the Data framework definition as below
E01C10 Classification  0-n   
E01D10.1 Classification scheme  1 Code LCF code list LCS 
E01D10.2 Scheme name  0-1 String Name or description of proprietary scheme 
E01D10.3 Scheme code  1 String  

compared to xml binding below
29 E01C10 classification 0-n   
30 E01D10.1 class-scheme-ref 1 string  
31 E01D10.2 class-term-ref 1 string

**Comment by franciscave** [comment]
Good catch! But I'm not sure what is the best fix for this issue. The Data Framework and the XML binding represent two inconsistent views of how classifications should be handled within LCF:

  -   The Data Framework assumes that classification schemes and codes are NOT fully controlled within LCF. The classification scheme (E01D10.1) can be either a standard scheme, such as Dewey, or proprietary, and is represented by a code value from code list LCS. If the scheme is proprietary, a scheme name should be provided (E01D10.2). There is no control over the choice of classification term itself (E01D10.3).

  -   The XML binding assumes that the classification schemes and codes are fully controlled within LCF. Each classification scheme is represented by a Classification entity (E10) and each code value within a classification scheme is represented by a Classification Term entity (E11). The classification composite then simply refers to a controlled scheme (E01D10.1) and an controlled term (E01D10.2).

These two views are clearly inconsistent, but a resolution is likely to break backwards compatibility - unless we take the view that we simply failed to update the Data Framework. But I think this will need discussion, because insisting that all classification schemes and terms be controlled within LCF might be considered too onerous.

An alternative, which I think could be implemented without breaking backwards compatibility (so could be included in v1.2.0), would be to allow the two views to co-exist: i.e. to allow implementers to choose between controlling classification schemes within LCF, or not, as they see fit. This would involve adding an extra composite to both the Data Framework and to the XML binding.

The Data Framework would look like this:

| *Id*       | *Element*                  | *SIP2 ID* | *Card.*[3](#Notes)                                                    | *Format*   | *Description*                  |
|------------|----------------------------|-----------|----------|------------|--------------------------------|
| ...              |                                         |                |               |                 |                                               |
| *E01C10*   | *External classification*           |           | 0-n      |            |  Classification scheme and term _not_ represented by LCF entities |
| E01D10.1   | Classification scheme      |           | 1        | Code       | LCF code list **[LCS](LCF-CodeLists.md#LCS)**          |
| E01D10.2   | Scheme name                |           | 0-1      | String     | Name or description of proprietary scheme                                                                                                         |
| E01D10.3   | Scheme code                |           | 1        | String     |                                |
| *E01C22*   | *LCF classification*           |           | 0-n      |            |  Classification scheme and term represented by LCF entities |
| E01D22.1   | Classification reference  |           | 0-1      | String     | Reference to a classification scheme record  |
| E01D10.3   | Classification term reference |           | 1        | String     |  Reference to a classification term record |
| ...              |                                         |                |               |                 |                                               |

The XML binding would look like this:

|        | *Element ID* | *XML structure*                  | *Card.* | *Data type* | *Notes* |
|--------|--------------|----------------------------------|---------|-------------|---------|
|  ...    |                     |                                           |         |             |         |
|  29    | E01C10       | other-classification         | 0-n     |             |         |
|  30    | E01D10.1    | class-scheme-type         | 0-n     | Code   |  [LCS](LCF-CodeLists.md#LCS) |
|  31    | E01D10.2    | class-scheme-name       | 0-n     | string  |         |
|  32    | E01D10.3    | class-term                      | 0-n     | string  |         |
|  33    | E01C22       | classification                   | 0-n     |             |         |
|  34    | E01D22.1    | class-scheme-ref            | 1         | string      |         |
|  35    | E01D22.2    | class-term-ref                 | 1        | string      |         |
|  ...    |                     |                                           |         |             |         |

Note that E01C22 is new in the Data Framework and corresponds to the existing composite in the XML binding, where the element IDs are changed to establish the correct correspondence. A new composite is introduced in the XML binding to correspond to the existing composite E01C10 in the Data Framework.

**Comment by kjeyakanthan** [comment]
Personally would be happy with the alternative as we do not ever want to break compatibility if we have a choice.

**Comment by franciscave** [comment]
The Data Framework also needs E01D22.2 Classification term record. See proposed documentation change.

**Comment by mdovey** [comment]
See Issue #207

**Comment by mdovey** [comment]
Superceded by decision to deprecate these entity types (#207)
