### ISSUE TITLE
Inclusion of entity objects when retrieving entity instance list

### ISSUE THREAD

**Issue by andrewdaye** [bic-org-uk/bic-lcf#191]
When retrieving an entity instance list (e.g. GET http://192.168.0.99:80/lcf/1.0/manifestations/1234567890/items from the documentation) the response provides the entity references which refer to the individual entities. For most applications, there then needs to be multiple subsequent calls for the individual entities.

Can the entities themselves ([instead of / as well as] references) be included in the initial response?

**Comment by franciscave** [comment]
I do seem to remember discussing this a while back. I believe it's a matter of REST principles: if you ask for a list of items, you expect to get back not the items themselves, but the URIs for each of those items. Maybe we could consider adding a function for retrieving a collection of entities, but this might raise performance/security concerns: for example, allowing a terminal to retrieve all manifestation entities or all patron entities.

**Comment by anthonywhitford** [comment]
@franciscave That's right. Our original discussions covered this. We'd agreed that network latency had been substantially improved, and that retrieving the list of URLs to individual resources, then fetching the resources that were actually needed was the desired model.

If we were to return the fully populated entity themselves, this would make the original call slower due to processing time on the server. I would suggest that the calling application would need to be structures to handle both the entity itself being populated and the URI to the entity being provided and requiring evaluation. If we were able to provide a flag on the request expressing the desire of the calling application, that could then be optional.

**Comment by franciscave** [comment]
I think we could use element Q02D03, which has not been implemented in the REST Web Service implementation of 02 Retrieve entity list. We could implement this as a query parameter. I think that, for the sake of completeness, we would need to add a new code value to code list IMD that would indicate that only the URIs should be returned in the response. This would be the default code value. This would also need to be added to code list MND. I think that code value '00' in list PNT is essentially what is needed in all three lists.

The query in the REST request, indicating that the entities themselves should be returned and not just the entity URIs would be something like:

        detail-requested=01

For reasons of backwards-compatibility, any terminal that were to include such a query parameter would have to be able to cope with a response that ignores this parameter and simply returns a list of entity URIs regardless.

**Comment by franciscave** [comment]
Here is my proposed change to the REST implementation of LCF function 02 Retrieve entity instance list:

In the Request:

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
|        | ...                  |                                      |                                       |              |                   |                    |
| 7     | Q02D03       |                                      | detail-requested | 0-1     | Code | *Added in v1.2.0.*<br/>May only be included if the key entity type is 'items'. Only two values from code list [IMD](LCF-CodeLists.md#IMD) are currently supported: '00' (default) indicates that the response is expected to contain a list of URIs for the items requested; '01' indicates that the response is expected to contain the full records for the items requested. See Note below.                                                           |
| 8     | Q02D04       |                                     | os:count              | 0-1     | int         | Implements the OpenSearch 1.1 'count' parameter                                                                                         |
| 9     | Q02D05       |                                     | os:startIndex         | 0-1     | int         | Implements the OpenSearch 1.1 'startIndex' parameter                                                                                  |

NOTE – (*Added in v1.2.0*) Query parameter 'detail-requested' implements Q02D03 in this binding, but only for requesting lists of items (entity type E02 'items'), not for any other entity type. If the server supports the use of this query parameter, the full records of the requested entity list may be returned in the response upon request as detailed above. However, the inclusion of this query parameter in the request may be ignored by the server, as if it had been omitted. Web service clients implementing this feature must be able to handle responses from servers that silently ignore the use of this query parameter and simply return a list if URIs. Servers implementing LCF v1.2.0 may either ignore this query parameter or return the requested list of item records in full within the response payload, but should not return an HTTP error response.

*Examples of a Request (revised in v1.2.0)*

    GET http://192.168.0.99:80/lcf/1.0/manifestations
    
    GET http://192.168.0.99:80/lcf/1.0/manifestations/1234567890/items
    
    GET http://192.168.0.99:80/lcf/1.0/manifestations/1234567890/items?os:count=10&os:startIndex=0

    GET http://192.168.0.99:80/lcf/1.0/manifestations/1234567890/items?detail-requested=01&os:count=4&os:startIndex=0

In the Response:

|       | *Element ID* | *XML structure*                         | *Card.* | *Data type* | *Notes*            |
|-------|--------------|-----------------------------------------|---------|-------------|--------------------|
|        | ...                   |                                                   |             |                     |                         |
| 9     | R02D06       | entity<br>href="{instance-uri}" | 0-n       | anyURI        | The 'href' attribute on the element 'entity' contains the URI for retrieving the instance of the specified entity type<br/>*Made non-mandatory in v1.0.1*                                                                                                       |
| 10   | R02D07        |                                                    | 0-n      |                     | *Added in v1.2.0*<br/>See Note below.                                                                                                                     |

NOTE – (*Added in v1.2.0*) LCF elements R02D06 and R02D07 are mutually exclusive. The Response may either contain a list of URIs or, if and only if the entity type is 'items' (E02), a set of item records encoded in XML format conforming to the XML binding for LCF information entity E02 Item in the [LCF information entity XML bindings specification](LCF-InformationEntityXMLBindings.md) and corresponding [XML schema](../lcf-schema/src/main/resources/lcf-v1.0-entities.xsd).

**Comment by franciscave** [comment]
Here is the proposed change to code list IMD to support the new code value '00':

### <a id="IMD"></a>IMD Item detailed information type

  *Code ID*   |*Code value*   |*Definition*                           |*Notes*
  ----------- |-------------- |-------------------------------------- |-------------------
  IMD01      |01             |All item detailed information          |A short-hand for requesting all detailed information that is available for the item.<br/>(*Added in v1.2.0*) May be used with LCF function 02 Retrieve entity instance list to request that the full records for each of the 
  ...              |                      |                                                         | 
  IMD12      |00                  |Item identifier only                                    |(*Added in v1.2.0*) Specifically included for use in element Q02D03 when requesting an entity instance list. Equivalent to omitting a request for detailed information. The server returns the identifier for each of the requested entity instances (R02D06), so that each can be retrieved individually using LCF function 01 Retrieve entity item information.

**Comment by franciscave** [comment]
We should probably make it clear in the REST implementation that the server response may only contain the item entities themselves if explicitly requested using the new query parameter.

**Comment by franciscave** [comment]
Following discussion with @anthonywhitford and @mdovey, I now realise that this issue affects retrieval of lists of entities of any type and not just items. 

What we discussed was a different solution to the one proposed above, which is to add a new element to the function 02 (retrieve entity instance list) request, specifying what kind of entity list is requested to be included in the response payload:

  -  a list of entity references, in which case the response would contain instances of R02D06
  -  a set of entities, in which case the response would contain instances of R02C07.

This new element (Q02D06) would be implemented in both the LCF Data Framework and the REST implementation.

The existing element Q02D03 would remain in the LCF Data Framework as currently, but does not need to be implemented in the REST implementation, since it addresses a different use case, which is to specify whether or not whole entity records or partial records (see #115) are returned in the response. Q02D03 could, in principle, be used with the new element.

The new element Q02D06 will need to use a new code list ELI Entity list information type, which will have two possible values:

  -  01 (Default value) A list of entity references is requested
  -  02 A set of entities is requested.

**Comment by franciscave** [comment]
Here is the proposed revision to the LCF Data Framework:

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------------|------------|---------|-----------|---------------------------------|
| ...              |                                         |                  |             |                |                                                |
| Q02D06   | Requested entity list type |                | 0-1       | Code       | LCF code list **[ELI](LCF-CodeLists.md#ELI)**<br/>*Added in v1.2.0*               |
| Q02D03     | Requested instance detailed information | | 0-n   | Code      | LCF code list **[MND](LCF-CodeLists.md#MND)**, **[IMD](LCF-CodeLists.md#IMD)** or **[PNT](LCF-CodeLists.md#PNT)**, depending upon entity type specified in Q02D01.<br/>Indicates the type of information to be included in the response. May be repeated if several types of information are requested, unless the code indicates that all details are to be included. If omitted, minimal details are included as determined by the LMS.                         |
| ...              |                                         |                  |             |                |                                                |

And here is the corresponding proposed change to the REST implementation:

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
| ...     |                     |                       |                             |           |               |                                           |
| 7     | Q02D06       |                       | list-type              | 0-1      | Code     | [ELI](LCF-CodeLists.md#ELI)<br/>*Added in v1.2.0*                                      |
| 7     | Q02D04       |                       | os:count              | 0-1     | int         | Implements the OpenSearch 1.1 'count' parameter                                                                                         |
| 8     | Q02D05       |                       | os:startIndex         | 0-1     | int         | Implements the OpenSearch 1.1 'startIndex' parameter                                                                                    |

And here is the proposed new code list:

### <a id="ELI"></a>ELI Entity list type - *Added in v1.2.0*

  *Code ID*   |*Code value*   |*Definition*   |*Notes*
  ----------- |-------------- |-------------- |-------------------------
  ELI01         | 01                | A list of entity references | Default value
  ELI02         | 02                | A set of entities / records |

**Comment by mdovey** [comment]
Related to issue #204

**Comment by franciscave** [comment]
I note that my proposal above for the REST implementation for including the entities themselves in response to a retrieve entity list request contains a typo: R02D07 should be R02C07.

**Comment by mdovey** [comment]
Closed as a specific solution to #218

**Comment by anthonywhitford** [comment]
Removing milestone "Someday.Major" as any further work will be considered and delivered under issue #218.
