### ISSUE TITLE
Look up patron by barcode etc.

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#215]
At present there appears to be no easy way to look up a patron by barcode or other identifiers. This is based on the notes for SEL03 which states (see E03D01), which suggests it does not also search E03D26,  E03C27 etc.

Similarly for searching manifestations, items, and locations via other identifiers (SEL01, SEL02, SEL04).

Either we need additional explicit selection criteria, or expand the note to include the additional id fields.

**Comment by franciscave** [comment]
When retrieving a list of entities that match particular selection criteria, the entity type is mandatory in the request (Q02D01). So it now strikes me as redundant that SEL01 - SEL04 all specify selection by entity ID. One generic criterion 'entity-id' would be sufficient. My suggestion would be that we specify a new code SEL17 with alpha value 'entity-id', to be used to select an entity (of the specified entity type) by its identifier. We can then specify that SEL01 - SEL04 should be used primarily for selecting by _additional_ identifier (E01C02, E02C02, E03C27 and E04C02 respectively, of any ID scheme) and that their use to select by entity ID be deprecated. 

Even with this change, it could be argued that there is still redundancy in SEL01 - SEL04, because we could have a single criterion 'entity-alternative-id'. So an alternative strategy would be to deprecate entirely the use of SEL01 - SEL04 and add two new codes for 'entity-id' and 'entity-alternative-id'.

**Comment by mdovey** [comment]
Seperating SEL01, SEL02, etc. allow us to do selections such as

http://server/lcf/1.0/loans?patron-id=patron1

which wouldn't be possible if there was a single entity-id

Admittedly, this can also be achieved using

http://server/lcf/1.0/patron/patron1/loans

however, if we introduce lists as planned in 1.2.0 then you could do

http://server/lcf/1.0/loans?patron-id=[patron1,patron2]

which isn't acheivable otherwise in a single call

**Comment by franciscave** [comment]
I now realise that the patron barcode is a special case, because it has its own element E03D26.  I therefore suggest that there needs to be code value in list SEL for barcode identifer _and_ each of the alternative identifiers (for those entities that have them), which could be paired with a query parameter specifying the ID scheme:

  -  patron-barcode-id
  -  alt-patron-id
  -  alt-patron-id-type (values from code list PNI)
  -  alt-manifestation-id
  -  alt-manifestation-id-type (values from code list MNI)
  -  alt-item-id
  -  alt-item-id-type (values from code list IMI)
  -  alt-location-id
  -  alt-location-id-type (values from code list LOI)
  -  alt-authority-id
  -  alt-authority-id-type (values from code list INS)

It would then, for example, be possible to search for loans by patron barcode ID:

    http://server/lcf/1.0/loans?patron-barcode-id=99999

or for items by ISBN-13:

    http://server/lcf/1.0/items?alt-manifestation-id-type=03&alt-manifestation-id=9780123456789.
