### ISSUE TITLE
write to a port in C++ and read in python simultaneously?

### ISSUE THREAD

**Issue by HaowenWeiJohn** [bic-org-uk/bic-lcf#262]
Hi, I have a question.
If I can write to a port in C++ and read in python simultaneously.
Thank you so much.

**Comment by franciscave** [comment]
This is a forum for raising issues with implementation of the BIC Library Communication Format, a data framework for communication between library management systems and terminal applications in libraries. Unless I have misunderstood your question, I think this is the wrong repository forum. I suggest you try one of the many Python-related repositories on GitHub. If you are trying to implement LCF, maybe you could re-phrase your question. Otherwise, sorry, we cannot help you.
