### ISSUE TITLE
PNI Code list query

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#304]
The PNI Code list is as follows:

Code ID | Code value | Definition | Notes
-- | -- | -- | --
PNI01 | 01 | Proprietary | ONIX code ‘01’
PNI02 | 16 | ISNI | ONIX code ‘16’
PNI03 | 18 | LCCN | ONIX code ‘17’
PNI04 | 21 | ORCID | ONIX code ‘21’
PNI05 | 31 | VIAF ID | ONIX code ‘31’

Why doe PNI03 have a different value to the ONIX code it corresponds to? Is this a typo, or deliberate?

**Comment by anthonywhitford** [comment]
This does feel like an error, as the other codes align with the ONIX list values.

**Comment by franciscave** [comment]
Good catch! This error exists in code list PNI from when it was introduced in LCF v1.0.1. Here is what ONIX code list currently contains:

Value | Description | Notes
-- | -- | --
... | ... | ...
17 | PND | Personennamendatei – person name authority file used by Deutsche Nationalbibliothek and in other German-speaking countries...
18 | NACO | A control number assigned to a Library of Congress Control Number (LCCN) Name Authority / NACO record
... | ... | ...

Since the error is only in the Notes column, we can correct the Note and mark it as corrected in v1.3.0. 

But that does leave open the question as to whether the Definition 'LCCN' is correct or not. We could leave it as it is, change it to 'NACO' or change it to 'LCCN / NACO'.

**Comment by franciscave** [comment]
I've checked back-issues of the ONIX code lists. Code '18' was described as 'LCCN' until Issue 51 (October 2020), when it changed from 'LCCN' to 'NACO'. I propose that we change the Definition of code PNI03 from 'LCCN' to 'NACO', and add a note on this change to the Notes field:

Code ID | Code value | Definition | Notes
-- | -- | -- | --
PNI01 | 01 | Proprietary | ONIX code ‘01’
PNI02 | 16 | ISNI | ONIX code ‘16’
PNI03 | 18 | NACO | ONIX code ‘18' (Definition was 'LCCN')<br/>*Definition updated and Note revised in Issue 5*
PNI04 | 21 | ORCID | ONIX code ‘21’
PNI05 | 31 | VIAF ID | ONIX code ‘31’
