### ISSUE TITLE
Implementation of RQT04 (Loan, renewal, reservation fee quotation request) in REST

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#84]
Code table RQT specifies

RQT04 | 04 | Loan / renewal or reservation fee quotation request only

however, this feature is not mapped into the REST implementation

**Comment by franciscave** [comment]
The REST implementation does include the query parameter 'confirmation=Y', which is equivalent to code value RQT02 (confirmation request). We could adopt a similar approach for quotation requests (RQT04), i.e. add a query parameter 'quotation=Y', which would obviously be mutually exclusive with 'confirmation=Y'.

**Comment by franciscave** [comment]
However, there is no mechanism at present for a response to a quotation request to provide the information that is requested without creating a charge. R11 and R16 will both need additional elements to be able to express the information that is requested, i.e. the charge amount and possibly the payment due date.

**Comment by franciscave** [comment]
Here is a suggested change to the data framework to allow the response to a check-out quotation request (request type RQT04) to contain a proposed charge type, charge description, payment due date-time, gross charge amount and charge currency:

#### Response

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------------|------------|---------|-----------|---------------------------------|
| R11D01     | Loan reference             |            | 0-1     | String    | LCF entity identifier for loan. Either a loan reference, or a copy of the loan record must be included in the response.                        |
| *R11C02*     | Loan entity record         |            | 0-1     |           | See E05                         |
| R11D03     | Item sensitive media warning |          | 0-1     | Code      | LCF code list **[MEW](LCF-CodeLists.md#MEW)**<br/>Same as E02D07. Flag indicating that the item contains a media component that is sensitive to some security setting devices.<br/>*Description modified in vx.x.0*                        |
| R11D04     | Desensitize item security  |            | 0-1     | Code      | LCF code list **[SCD](LCF-CodeLists.md#SCD)**<br/>Same as E02D08. Flag indicating whether the security should or should not be desensitized / removed on check-out.<br/>*Description modified in vx.x.0*                                  |
| R11D05     | Charge reference           |            | 0-1     | String    | Reference to charge created with this loan. |
| R11D07     | Proposed charge type          |        | 0-1     | Code      | LCF code list **[CHT](LCF-CodeLists.md#CHT)**<br/>Only to be included in response to a check-out request of type RQT04 (requesting quotation only). Same as E07D03.<br/>*Description modified in vx.x.0*    |
| R11D08     | Proposed charge description |      | 0-1     | String     | Description of quoted charge. Only to be included in response to a check-out request of type RQT04 (requesting quotation only). Same as E07D05.<br/>*Description modified in vx.x.0*    |
| R11D09     | Proposed charge payment due date-time     |      | 0-1     | DateTime      | The date and optionally time on which the proposed charge would become due for payment. Only to be included in response to a check-out request of type RQT04 (requesting quotation only). Same as E07D11.<br/>*Description modified in vx.x.0*    |
| R11D10     | Proposed charge currency     |      | 0-1     | Value      | Currency value of proposed charge. Only to be included in response to a check-out request of type RQT04 (requesting quotation only). Same as E07D12.<br/>*Description modified in vx.x.0*    |
| R11D11     | Proposed charge currency     |      | 0-1     | Code      | ISO three-letter currency code, e.g. ‘GBP’. Only to be included in response to a check-out request of type RQT04 (requesting quotation only). Same as E07D13.<br/>*Description modified in vx.x.0*    |
| R11D06     | Digital content access link |   | 0-1     | String    | Non-persistent link to be used by the patron to access checked-out digital content<br/>*Added in v1.0.1*                                                |

**Comment by andrewdaye** [comment]
There are a number of actions where a server implementation may require a prompt to be acknowledged by the client prior to completing the initially requested action. 

1. Creating a reservation
2. Creating a loan
3. Renewing a loan

These prompt acknowledgements may not necessarily be confined to the imposition of charges, and are in some instances blockers (depending on the user authorisation currently in place). E.g. a patron-level access to the system may not be able to "accept" a block on that patrons account, whilst a staff level user token may allow for that to be accepted.

As such, the response to the initial request would need to allow for a 0..n list of conditions, with a code and description, along with the detail of whether this user can accept those conditions.

Once the user has been prompted (or the client application has been configured to auto-accept), there also then needs to be a way to pass the conditions that have been accepted back to the server. In most implementations, this is acheived by passing a comma-separated list of the "code" values for the conditions.

This has been implemented in three different ways that we have seen so far:

1. In the Query string (e.g. "&promptack=COD1,CODE2,CODE3" ) 
2. As a header in the HTTP request (e.g. x-prompt-acknowledged: CODE1,CODE2,CODE3)
3. As an extension of the body in the request (e.g. { "promptsAcknowledged" : "CODE1,CODE2,CODE3" } ).

It would be helpful for this to be standardised.

**Comment by franciscave** [comment]
This issue was discussed at the Technical Panel meeting on 20 April 2021. It was agreed to draft changes to the LCF Data Framework and REST implementation to address the additional use cases described in @andrewdaye's most recent comment. Where a user acknowledgement is required in order for a request to be accepted, the server initially denies the request, and the exception condition includes a message that needs to be acknowledged by the user if and when they repeat the request.

Here is an initial draft of changes to the LCF Data Framework:

### R00 Elements common to responses

| *Id*            | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|-------------|------------------------|------------|---------|-----------|------------------------------|
| ...                |                                   |                 |              |                |                                           |
| *R00C05*   | *Exception condition*      |            | 0-n     |           | Response if there is an exception condition, in which case this and, optionally, one or more of the following message elements terminate the response.|
| R00D05.1   | Condition type             |            | 1       | Code      | LCF code list **[EXC](LCF-CodeLists.md#EXC)**<br/>Response code will often be specific to the function requested.                                                         |
| R00D05.2   | Reason request denied      |            | 0-1     | Code      | LCF code list **[RDN](LCF-CodeLists.md#RDN)**<br/>Used if R00D05.1 contains '08' (request denied)                                                                       |
| R00D05.3   | Element reference          |            | 0-1     | String    | A reference (e.g. the LCF element ID) that uniquely identifies the element in the request payload that generated the exception condition.            |
| *R00C06*   | *Response message*         | AF / AG    | 0-n     |           | Composite element containing text to display or print on terminal.                                                                                  |
| R00D06.1   | Message display type       |            | 1       | Code      | LCF code list **[MGT](LCF-CodeLists.md#MGT)**           |
| R00D06.2   | Message to display         |            | 1-n     | String    | Repeatable if display type is ‘single line’                          | 
| R00D06.3   | Acknowledgement code |             | 0-1    | String    | Library-specific code to be included in a repeat request, for the request to be accepted; only included if R00D06.1 contains '10'  (request requires acknowledgement)<br/>*Added in v1.x.0* |

Here is an initial draft of changes to the LCF Code Lists:

### <a id="RDN"></a>RDN Reason for inability to approve request

  *Code ID*   |*Code value*   |*Definition*                      |*Notes*
  -------------- |-------------- |-----------------------------------|----------------------
  ...                   |                      |                                                   |
  RDN09          | 09                 |Unable to accept some/all payment items in request – see detail   |  
  RDN10          | 10                 | Request requires acknowledgement - see response message |  *Added in Issue 5*

### <a id="MGT"></a>MGT Message display type

  *Code ID*   |*Code value*   |*Definition*                                 |*Notes*
  ----------- |-------------- |-------------------------------------------- |---------
  MGT01       |01             |Whole message (e.g. for screen display), not requiring acknowledgement      | *Revised in Issue 5*
  MGT02       |02             |Single line of message (e.g. for printing)   |
  MGT03       |03             | System message (not normally for display)   |
  MGT04       |04             | Whole message, requires acknowledgement | *Added in Issue 5*

**Comment by mdovey** [comment]
Agreed at technical panel on the 3/11/2021, to incorporate these changes.

**Comment by franciscave** [comment]
See pull request #288.

**Comment by franciscave** [comment]
Pull request #288 only partially resolves this issue, i.e. how a server can indicate that there is a charge, by refusing the initial request, and including a message indicating that an acknowledgement is required in the request. The following are also needed:

-  the ability to provide details of any proposed charge in the response;
-  the ability to include a library-specific acknowledgement code in the (repeated) request.

The solution to the first of these was provided in my proposed changes to R11 on 9 February 2021 - see above comment. 

The solution to the second of these would effectively resolve #292, and I propose that this can be done simply by adding a new element Q00D10 to Q00 Elements common to requests:

### Q00 Elements common to requests

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------------|------------|---------|-----------|---------------------------------|
| ...   | ...                  | ...         | ...     |           | ...              |
| Q00D07     | Request ID                 |            | 0-1     | String    | An ID of a request. If included in a request, it must also be included in the LMS response.                                                         |
| Q00D08     | Request date-time          |            | 0-1     | DateTime  | ISO date-time<br/>The date-time at which the terminal application user submitted the request. Normally generated by the application.              |
| Q00D09     | Previous request ID        |            | 0-1     | String    | Used when cancelling a previous request, in which case this element contains the identifier of the previous request (see element Q00D07).      |
| Q00D10     | Acknowledgement code  |           | 0-1     | String    | Used when repeating a previous request that was denied by the server, when the server response contains reason request denied code RDN10 in R00D05.2 and this acknowledgement code in R00D06.3.<br/>*Added in vx.x.0* |

Note that the use of Q00D10 would make redundant the use of other mechanisms for acknowledging a charge: Q11D07 and Q16D10.

This will necessitate changes to the REST Web Service Specification, to be specified in a separate comment.

**Comment by franciscave** [comment]
The proposal I made on 9 February 2021 to modify the check-out response R11 is not satisfactory from various points of view:

-  It only works for check-out or renewal, but not for making a reservation or any other request that could incur a charge.
-  It suggests that a charge quotation is part of a successful server response, but the proposed changes to R00 imply that the quotation is part of an exception server response (request denied), but this is not the case.

A possible solution would be to integrate the charge quotation elements in the exception response R00 as follows:

### R00 Elements common to responses

| *Id*            | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|-------------|------------------------|------------|---------|-----------|------------------------------|
| ...                | ...                               | ...              | ...          | ...             | ...                                        |
| *R00C05*   | *Exception condition*      |            | 0-n     |           | Response if there is an exception condition, in which case this and, optionally, one or more of the following message elements terminate the response.|
| R00D05.1   | Condition type             |            | 1       | Code      | LCF code list **[EXC](LCF-CodeLists.md#EXC)**<br/>Response code will often be specific to the function requested.                                                         |
| R00D05.2   | Reason request denied      |            | 0-1     | Code      | LCF code list **[RDN](LCF-CodeLists.md#RDN)**<br/>Used if R00D05.1 contains '08' (request denied)                                                                       |
| R00D05.3   | Element reference          |            | 0-1     | String    | A reference (e.g. the LCF element ID) that uniquely identifies the element in the request payload that generated the exception condition.            |
| *R00C06*   | *Response message*         | AF / AG    | 0-n     |           | Composite element containing text to display or print on terminal.                                                                                  |
| R00D06.1   | Message display type       |            | 1       | Code      | LCF code list **[MGT](LCF-CodeLists.md#MGT)**           |
| R00D06.2   | Message to display         |            | 1-n     | String    | Repeatable if display type is ‘single line’                          | 
| R00D06.3   | Acknowledgement code |             | 0-1    | String    | Library-specific code to be included in a repeat request, for the request to be accepted. Only to be included if R00D06.1 contains code RDN10 (request requires acknowledgement) and the request has to acknowledge an applicable charge.<br/>*Added in vx.x.0* |
| *R00C07*      | *Proposed charge*          |              | 0-1     |               | Charge that applies if when R00D05.2 contains contains code RDN10.<br/>*Added in vx.x.0*   |
| R00D07.1     | Charge type          |        | 0-1     | Code      | LCF code list **[CHT](LCF-CodeLists.md#CHT)**    |
| R00D07.2     | Charge description |      | 0-1     | String     | Description of proposed charge.    |
| R00D07.3     | Charge payment due date-time     |      | 0-1     | DateTime      | The date and optionally time on which the proposed charge would become due for payment.  |
| R00D07.4     | Gross charge amount     |      | 0-1     | Value      | Currency value of proposed charge.     |
| R00D07.5     | Charge currency     |      | 0-1     | Code      | ISO three-letter currency code, e.g. ‘GBP’.   |

A corresponding modification to the XML binding for exception conditions will also be needed.

**Comment by franciscave** [comment]
Here is the corresponding proposed modification to the XML binding for Exception Conditions:

EXCEPTION CONDITIONS
--------------------

|       | *Element ID* | *XML structure*             | *Card.* | *Data type* | *Notes* |
|-------|--------------|-----------------------------|---------|-------------|---------|
| **1** |              | **lcf-exception<br/>xmlns=<br/>"http://ns.bic.org/lcf/1.0"**                                 |         |             | **Top-level&nbsp;element**<br/>*'version' attribute removed in v1.0.1*                                                        |
| **2** | **R00C05**   | **exception-condition**     | **1-n** |             |         |
| **3** | **R00D05.1** | **condition-type**          | **1**   | **Code**    | **[EXC](LCF-CodeLists.md#EXC)** |
|   4   | R00D05.2     | reason-denied               | 0-1     | Code        | [RDN](LCF-CodeLists.md#RDN)     |
|   5   | R00D05.3     | element-id                  | 0-1     | string      |         |
|   6   | R00C06       | message                     | 0-n     |             |         |
|   7   | R00D06.1     | message-type                | 1       | string      | [MGT](LCF-CodeLists.md#MGT)     |
|   8   | R00D06.2     | message-text                | 1-n     | string      |         |
|   9   | R00D06.3     | acknowledgement-code | 0-1    | string      |  *Added in vx.x.0*       |
|  10  | R00C06.4     | applicable-charge          | 0-1    |                 |  *Added in vx.x.0*       |
|  11  | R00D06.4.1  | charge-type                  | 0-1    | Code        | [CHT](LCF-CodeLists.md#CHT)     |
|  12  | R00D06.4.2  | description                    | 0-1    | string       |         |
|  13  | R00D06.4.3  | payment-due-date        | 0-1    | dateTime |         |
|  14  | R00D06.4.4  | charge-amount             | 1       | decimal    |         |
|  15  | R00D06.4.5  | currency                        | 0-1    | Code       | ISO currency code        |

**Comment by franciscave** [comment]
The REST Web Service Specification already includes an implementation note 7 on exception conditions:

> #### 7. Exception conditions in RESTful web service responses
> 
> In a RESTful web service implementation exception condition responses should generally be carried by an HTTP response status code. Where appropriate, in order to be more specific about the exception conditions that apply, an XML payload that conforms to the LCF Exception Conditions XML schema, may be included in the response, if it is valid to include a payload with the specific HTTP response status code.
> 

One option would therefore be to extend this section with examples of exception conditions, including examples of the use of reason for denial code RDN10, the acknowledgement code in R00D06.3 and an applicable charge in R00C06.4. However this could overload this section, so perhaps better to add a new section 10 showing examples of the use of exception conditions to require acknowledgement in the request.

**Comment by franciscave** [comment]
Following separate discussion with @mdovey and @anthonywhitford, it is suggested that the initial HTTP response from the server containing the exception condition should, in the case of both this issue and #292, be a 418... er, sorry a 428 Precondition required. Any objections to that? I'll prepare examples on that basis.

**Comment by franciscave** [comment]
This new approach to acknowledging a charge for check-out or reservation overlaps in functional terms with the following existing features in LCF:

-  A check-out request containing Q11D07 Charge acknowledged.
-  A reservation request containing Q16D10 Charge acknowledged.
-  In response to a check-out or reservation request, an exception condition in which the reason for denial of the request is expressed by code RDN04 (No fee acknowledgement in the request).

It is therefore proposed to make it clear that:

-  In a check-out request either Q11D07 (Charge acknowledged) or Q00D10 (Acknowledgement code) may be used, but not both.
-  In a reservation request either Q16D10 (Charge acknowledged) or Q00D10 (Acknowledgement code) may be used, but not both.
-  In an exception condition response to a check-out or reservation request:
    - if R00D05.2 contains code RDN04, the message R00C06 shall not contain either R00D06.3 or R00C06.4;
    - if R00D05.2 contains code RDN10, the message R00C06 shall contain R00D06.3 and may also contain R00C06.4.

We should consider stating (in the Framework and in the REST Web Services Specification) that server implementations are not required to support both the charge acknowledgement mechanisms, and are encouraged to support the new mechanism. We should therefore also consider deprecating the use of code RDN07 and element Q11D07 and Q16D10, to encourage implementers to support the new generic mechanism.

**Comment by franciscave** [comment]
*Proposed revisions to the REST Web Service Specification:*
-  *A NOTE is added to implementation note 7.*
-  *Query parameter acknowledgement-code is added to the check-out request and to the reservation request.*
-  *Two examples of exception conditions, requiring an acknowledgement code to be included in the repeated request, are added to the check-out response section.*
-  *A note is added to the reservation response section.*

*Here are the details:*

#### 7. Exception conditions in RESTful web service responses
 
In a RESTful web service implementation exception condition responses should generally be carried by an HTTP response status code. Where appropriate, in order to be more specific about the exception conditions that apply, an XML payload that conforms to the LCF Exception Conditions XML schema, may be included in the response, if it is valid to include a payload with the specific HTTP response status code. 

NOTE – *(Added in vx.x.0)* See [11 Checkout/renewal](#checkout) for examples of the use of exception conditions to require a client to repeat a request with an acknowledgement code. 

...

## 11 Check-out / renewal

The difference between a check-out and renewal is that in the latter case an existing, active loan of the same item to the same patron must exist. It should not be necessary for the terminal application to know whether an item is already on loan to the patron in question, because the LMS will be able to determine whether this is the case or not. A single function will therefore normally suffice.

NOTE – *(added in vx.x.0)* This REST web service implementation of the LCF Data Framework does not implement a mechanism for specifying the type of a renewal, which in the Data Framework is represented by element Q11D02. In the Data Framework this element serves two purposes: 

  -  to indicate if the request is to renew all items checked out to that patron; 
  
  -  to indicate whether the request is being made by the patron directly or by a third party. 
  
Renewal of a large number of loan items in a single request would place an arbitrarily large processing burden on the server, obliging the server to check and update the status of all the patron's loans before responding to the request, which could involve an unacceptable response-time. For this reason the ability to renew all items on loan is not supported. To renew all a patron's loans, the terminal client must retrieve a list of all the patron's loans and request renewal of each in turn.

In a REST web service implementation it is not necessary to have a separate element or parameter to indicate whether it is the patron or a third party making the request, because this is already indicated by ensuring that the user making the request is authenticated in the request header.

The request is formulated using the HTTP POST method.

### Format for request URI 

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
| **1** |              | **/lcf**              |                       | **1**   |             | LCF initial segment |
| **2** |              | **/1.0**              |                       | **1**   |             | LCF version number. All 1.x.x. versions of this specification will use the string "1.0" here. |
| **3** |              | **/loans**            |                       | **1**   |             |              |
| 4     | Q11D01       |                       | confirmation          | 0-1     | Y           | Implements request type RQT02 confirmation request.<br/>*(Added in vx.x.0)*             |
| 5     | Q11D07       |                       | charge-acknowledged   | 0-1     | Y           | Inclusion of this query parameter with any value other than 'n' or 'N' should be interpreted as indicating that a charge may be created for this loan. Must not be used in combination with an acknowledgement code<br/>*Revised in vx.x.0*|
| 6     | Q00D10       |                       | acknowledgement-code | 0-1    | String    | This query parameter is included in a repeated request, when an exception response to the initial request contained reason for denial code '10' (RDN10 Request requires acknowledgement) and the exception response message contained this string in the acknowledgement code element (R00D06.3).<br/>*Added in vx.x.0*|

A new check-out is performed by creating a new loan record, using LCF function 03 (see above), e.g.

    POST http://192.168.0.99:80/lcf/1.0/loans

Request to confirm a new check-out, which the LMS may not normally deny (equivalent to the SIP2 "no block" flag) *(Modified in vx.x.0)*, is indicated by including the 'confirmation' parameter in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/loans?confirmation=Y

If a charge is applicable, the response may report an exception unless the 'charge-acknowledged' parameter is included in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/loans?charge-acknowledged=Y

An XML document that conforms to the XML schema for a loan entity (E05) must be uploaded with the request.

In the case of a renewal, the creation of a new loan may be more readily performed by first retrieving the current loan, then using it as a basis for the new loan. However, this could be performed by the LMS, so it should not be necessary for the terminal application to carry out these additional steps.

It is assumed that the other record functions (check that copy can be loaned, check patron status, cancel reservation if any, create charge record if appropriate, update patron and copy records) are performed on the server side. If any of these functions have to be done manually by the terminal application client, a sequence of basic retrieval, modification and deletion functions may be used for this purpose.

### Response

The response to a check-out or renewal may be the same response as for creating any entity, i.e. status code 201 (Created) and a Location field in the HTTP header, or it may contain an XML payload that conforms to the following schema. The advantage of including the XML payload in the response is that the terminal application will thereby be alerted by the inclusion of any of R11D03 – R11D05 in the response, rather than having to retrieve the newly-created loan in order to determine whether or not sensitive media are involved or security needs de-sensitization, or what charge has been made for the loan.

|       | *Element ID* | *XML structure*                          | *Card.* | *Data type* | *Notes*           |
|-------|--------------|------------------------------------------|---------|-------------|-------------------|
| **1** |              | **lcf-check-out-response** | **1**   |             | **Top-level message element**<br/>*'version' attribute removed in v1.0.1*                                                                  |
| ~~2~~ | ~~R11D01~~   | ~~loan-ref~~                             | ~~0-1~~ | ~~anyURI~~  | ~~One of R11D01, R11C02 or R11D03 must be included in the response.~~ <br/>*Removed in v1.2.0*                                              |
| **3** | **R11C02**   | **loan**                                 | **1**   |             | **See E05**<br/>*Cardinality changed in v1.2.0* |
| 4     | R11D03       | media-warning                            | 0-1     | Code        | [MEW](LCF-CodeLists.md#MEW) – Omitted if responding to a renewal                                                              |
| 5     | R11D04       | security-desensitize                     | 0-1     | Code        | [SCD](LCF-CodeLists.md#SCD) – Omitted if responding to a renewal                                                              |
| 6     | R11D05       | charge-ref                               | 0-1     | anyURI      |                   |
| 7     | R11D06       | access-link                              | 0-1     | anyURI      | *Added in v1.0.1*    |

*Example of a Response XML payload:*

    <lcf-check-out-response xmlns="http://ns.bic.org/lcf/1.0">
     <loan>
      <identifier>...</identifier>
      <patron-ref>...</patron-ref>
      <item-ref>...</item-ref>
      <start-date>...</start-date>
      <loan-status>...</loan-status>
     </loan>
     <sensitive-media-warning>00</sensitive-media-warning>
    </lcf-check-out-response>

#### <a name="checkout"></a>Exception condition response when check-out request requires an acknowledgement code *(Added in vx.x.0)*

A exception condition response may be used to convey a warning message to the terminal user, which the user must acknowledge before the request can be accepted. Here are two examples of situations where this could apply:

**Example 1: Item being checked out has been checked out previously to the same patron**

A library may wish to warn the user that the item being checked out has previously been lent to the same patron. The initial check-out request would be refused by the server using HTTP response code 428 (Precondition required) and the response would include the details of the exception condition as an XML payload such as the following:

```
<exception-condition>
  <condition-type>07</condition-type>
  <reason-denied>10</reason-denied>
  <message>
    <message-type>04</message-type>
    <message-text>Item xxx lent previously to this patron</message-text>
    <acknowledgement-code>ack123456</acknowledgement-code>
  </message>
</exception-condition>
```

This response would require that the client repeat the request with the acknowledgement code included as the value of query parameter `acknowledgement-code` in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/loans?acknowledgement-code=ack123456


**Example 2: Item being checked out will incur the specified charge**

A library may wish to warn the user that the item being checked out will incur a charge, and specify the amount of the charge. The initial check-out request would be refused by the server using HTTP response code 428 (Precondition required) and the response would include the details of the exception condition as an XML payload such as the following:

```
<exception-condition>
  <condition-type>07</condition-type>
  <reason-denied>10</reason-denied>
  <message>
    <message-type>04</message-type>
    <message-text>A charge is applicable for the item(s) being checked out as specified.</message-text>
    <acknowledgement-code>ack987654</acknowledgement-code>
    <applicable-charge>
      <charge-type>06</charge-type>
      <charge-amount>nn.nn</charge-amount>
    </applicable-charge>
  </message>
</exception-condition>
```

This response would require that the client repeat the request with the acknowledgement code included as the value of query parameter `acknowledgement-code` in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/loans?acknowledgement-code=ack987654

...

## 16 Reserve manifestation / item

### Request

The request is formulated using the HTTP POST method.

### Format for request URI 

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
| **1** |              | **/lcf**              |                       | **1**   |             | LCF initial segment |
| **2** |              | **/1.0**              |                       | **1**   |             | LCF version number. All 1.x.x. versions of this specification will use the string "1.0" here. |
| **3** |              | **/reservations**     |                       | **1**   |             |              |
| 4     | Q16D01       |                       | confirmation          | 0-1     | Y           |              |
| 5     | Q16D10       |                       | charge-acknowledged   | 0-1     | Y           | Inclusion of this query parameter with any value other than 'n' or 'N' should be interpreted as indicating that a charge may be created for this loan.                                                                                                 Must not be used in combination with an acknowledgement code<br/>*Revised in vx.x.0*|
| 6     | Q00D10       |                      | acknowledgement-code | 0-1    | String    | This query parameter is included in a repeated request, when an exception response to the initial request contained reason for denial code '10' (RDN10 Request requires acknowledgement) and the exception response message contained this string in the acknowledgement code element (R00D06.3).<br/>*Added in vx.x.0*|

A reservation is performed by creating a new reservation record, using LCF function 03 (see above), e.g.

    POST http://192.168.0.99:80/lcf/1.0/reservations

Request to confirm a reservation, which the LMS may not normally deny, is indicated by including the 'confirmation' parameter in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/reservations?confirmation=Y

If a charge is applicable, the response may report an exception unless the 'charge-acknowledged' parameter is included in the request, e.g.

    POST http://192.168.0.99:80/lcf/1.0/reservations?charge-acknowledged=Y

An XML document that conforms to the XML schema for a reservation entity (E06) must be uploaded with the request.

### Response

The response is the same as for creating any entity – see function 03 above. *[Changed in v1.0.1.]*

NOTE – *(added in vx.x.0)* See [11 Checkout/renewal](#checkout) for examples of the use of exception conditions to require a client to repeat a request with an acknowledgement code. These can equally be used in response to reservation requests as in response to check-out requests.

**Comment by franciscave** [comment]
Here is the corresponding modification required to requests in the REST implementations of LCF functions 11 Check-out / renewal and 16 Reserve manifestation / item:

## 11 Check-out / renewal

...

### Format for request URI 

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
| **1** |              | **/lcf**              |                       | **1**   |             | LCF initial segment |
| **2** |              | **/1.0**              |                       | **1**   |             | LCF version number. All 1.x.x. versions of this specification will use the string "1.0" here. |
| **3** |              | **/loans**            |                       | **1**   |             |              |
| 4     | Q11D01       |                       | confirmation          | 0-1     | Y           | Implements request type RQT02 confirmation request.<br/>*(Added in vx.x.0)*             |
| 5     | Q11D07       |                       | charge-acknowledged   | 0-1     | Y           | Inclusion of this query parameter with any value other than 'n' or 'N' should be interpreted as indicating that a charge may be created for this loan. Must not be used in combination with an acknowledgement code<br/>*Revised in vx.x.0*|
| 6     | Q00D10       |                       | acknowledgement-code | 0-1    | String    | This query parameter must be include in a repeated request, when an exception response to the initial request contained reason for denial code '10' (RDN10 Request requires acknowledgement) and at least one exception response message contained an acknowledgement code (R00D06.3). The value of this query parameter must be a comma-delimited, concatenated string of all the acknowledgement codes in the exception response.<br/>*Added in vx.x.0*|

...

## 16 Reserve manifestation / item

...

### Format for request URI 

|       | *Element ID* | *URI Path segment(s)* | *URI Query parameter* | *Card.* | *Data type* | *Notes*      |
|-------|--------------|-----------------------|-----------------------|---------|-------------|--------------|
| **1** |              | **/lcf**              |                       | **1**   |             | LCF initial segment |
| **2** |              | **/1.0**              |                       | **1**   |             | LCF version number. All 1.x.x. versions of this specification will use the string "1.0" here. |
| **3** |              | **/reservations**     |                       | **1**   |             |              |
| 4     | Q16D01       |                       | confirmation          | 0-1     | Y           |              |
| 5     | Q16D10       |                       | charge-acknowledged   | 0-1     | Y           | Inclusion of this query parameter with any value other than 'n' or 'N' should be interpreted as indicating that a charge may be created for this loan.                                                                                                 Must not be used in combination with an acknowledgement code<br/>*Revised in vx.x.0*|
| 6     | Q00D10       |                      | acknowledgement-code | 0-1    | String    | This query parameter must be include in a repeated request, when an exception response to the initial request contained reason for denial code '10' (RDN10 Request requires acknowledgement) and at least one exception response message contained an acknowledgement code (R00D06.3). The value of this query parameter must be a comma-delimited, concatenated string of all the acknowledgement codes in the exception response.<br/>*Added in vx.x.0*|

**Comment by mdovey** [comment]
Added to documentation as agreed in April 2023 Technical Committee
